
version: 2

models:
  - name: movies
    description: "This table contains details about movies."
    columns:
      - name: id
        description: "Unique identifier for the movie."
        tests:
          - unique
          - not_null
      - name: title
        description: "Title of the movie."
        tests:
          - not_null
      - name: released_year
        description: "Year the movie was released."
        tests:
          - not_null
      - name: imdb_certificate
        description: "The IMDB Certificate of the movie."
        tests:
          - not_null
      - name: rating
        description: "Rating of the movie."
        tests:
          - not_null
      

  - name: actors
    description: "This table contains details about actors."
    columns:
      - name: id
        description: "Unique identifier for the actor."
        tests:
          - unique
          - not_null
      - name: actor_name
        description: "The name of the actor."
        tests:
          - not_null


  - name: genres
    description: "This table contains details about movie's genres."
    columns:
      - name: id
        description: "Unique identifier for the genre."
        tests:
          - unique
          - not_null
      - name: genre_name
        description: "The name of the genre."
        tests:
          - not_null


  - name: movies_and_actor
    description: "This table maps movies to the actors that starred in them."
    columns:
      - name: movie_id
        description: "Identifier for the movie."
        tests:
          - not_null
      - name: actor_id
        description: "Identifier for the actor."
        tests:
          - not_null


  - name: movies_and_genre
    description: "This table maps movies to the genre."
    columns:
      - name: movie_id
        description: "Identifier for the movie."
        tests:
          - not_null
      - name: genre_id
        description: "Identifier for the genre."
        tests:
          - not_null
  
  
  - name: movie_ratings
    description: "This model aggregates movie data and calculates the average rating for each movie."
    columns:
      - name: movie_id
        description: "The unique identifier for each movie."
        tests:
          - unique
          - not_null

      - name: title
        description: "The title of the movie."
        tests:
          - not_null

      - name: released_year
        description: "The release year of the movie."
        tests:
          - not_null

      - name: imdb_certificate
        description: "The IMDB Certificate of the movie."
        tests:
          - not_null

      - name: rating
        description: "The rating for the movie."
        tests:
          - not_null

      - name: actor_count
        description: "The number of actors in the movie."
        tests:
          - not_null

      - name: avg_actor_rating
        description: "The average rating of movies that the actors of this movie have acted in."
        tests:
          - not_null

  - name: movie_actors
    description: "This model aggregates movie title and name of actor."
    columns:
      - name: movie_title
        description: "The title of the movie."
        tests:
          - not_null

      - name: actor_name
        description: "The actor name of this movie have acted in."
        tests:
          - not_null

  - name: movie_genres
    description: "This model aggregates movie title and their genre."
    columns:
      - name: movie_title
        description: "The title of the movie."
        tests:
          - not_null

      - name: genre
        description: "The genre name of this movie."
        tests:
          - not_null